### ISSUE TITLE
Is env.yml file missing? 

### ISSUE THREAD

**Issue by yitongqi** [NICALab/SUPPORT#1]
I cloned the repository then tried to create a new environment, but it seems that the env.yml file is missing.

**Comment by EOMMINHO** [comment]
Thanks for your interest in our program. We will fix it in a few hours!

**Comment by EOMMINHO** [comment]
Code fixed!

**Comment by yitongqi** [comment]
by the way, I needed to change channels to conda-forge. 
defaults does not get all the packages

**Comment by EOMMINHO** [comment]
Thank you for letting me know.
I will figure it out soon!
