### ISSUE TITLE
RGB images

### ISSUE THREAD

**Issue by sdalumlarsen** [NICALab/SUPPORT#14]
Hello,

My lab has previously used SUPPORT to great satisfaction on a grayscale structural dataset. We would like to also use it on a behavioural dataset of RGB mp4 videos in low light conditions. Per the github, SUPPORT only accepts tif, so i converted it to a RGB tif stack, and tried to train SUPPORT using a 1000 frame snippet (So dimensions were [1000, 1024, 1280, 3]) in the train_gui, however it was not fond of the 4th dimension added by RGB. I was wondering if SUPPORT is capable of running with RGB files and I am simply oblivious as to how? If not I can of course simply split the channels and add them as separate videos and then stitch them together afterwards but as there is information in the correlation between colors, I would prefer not to.

Thank you for your time.

best,
Silas

**Comment by EOMMINHO** [comment]
Hi Silas,
Unfortunately, the algorithm does not support the RGB stack. (You need to convert the RGB file to grayscale and stitch it afterward as you said).
We will keep that point on our update list. Thanks!
