### ISSUE TITLE
Using GUI to denosie my movie but the output is only one image?

### ISSUE THREAD

**Issue by ZyHUpenn** [NICALab/SUPPORT#4]

**Comment by SteveJayH** [comment]
In our side, we're not sure if that issue exist... With test_GUI, I checked that denoised.tif contains multiple frames, not only one frame.
Did you tried with demo data at `src/sample_data.tif` ??

I just tried as followings.
1. `python -m src.GUI.test_GUI` to open GUI.
2. Browse src/sample_data.tif. Then, start index will be 1 and end index will be displayed as 300. Also, save path will be automatically selected as `data/SUPPORT/current_timestamp/`.
3. Press Run button. And if you go to the save path, you may see the size of `denoised.tif` will keep increasing as the inference goes on. I'm not sure of cv2.imread, but if I open the `denoised.tif` with ImageJ/fiji, the data contains 300 frames. 

If you did not tried with demo data, please check if our code with this data works well.
Let me know if it works or not.

Also, if the code with demo data works well, but not for your custom data, let me know. We can find if the code is going wrong with your data.

**Comment by ZyHUpenn** [comment]
Right, when I open the denoised.tif in imageJ it shows all the frames. The code should be all good, thank you very much! Maybe I need to find another way to load it on python, the denoised.tif 's 32-bit format may cause cv2's problem I guess anyway.

**Comment by SteveJayH** [comment]
Ah okay, I also do not use cv2 when deal with these microscopy images (I feel like they are well suited to 8bit "natural" images).
I think tifffile package or skimage.io package will be nice to load 16 or 32-bit images.
(Internally, skimage.io will use tifffile to read and write with tif images)

**Comment by ZyHUpenn** [comment]
Yes, the skimage cannot deal with this problem. I used matlab to open the
file then it works. Hopefully it will help you.
