### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by fabricesenger** [NICALab/SUPPORT#9]
Hi ,

I started the install of SUPPORT on a windows11 machine, when i try to start the guy a get following error. Thank you in advance for your help.

Fabrice Senger.

(SUPPORT) C:\Users\fabrice_senger\SUPPORT>python -m src.GUI.test_GUI
Traceback (most recent call last):
  File "C:\Users\fabrice_senger\miniconda3\envs\SUPPORT\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fabrice_senger\miniconda3\envs\SUPPORT\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fabrice_senger\SUPPORT\src\GUI\test_GUI.py", line 29, in <module>
    from PIL.ImageQt import ImageQt
ImportError: cannot import name 'ImageQt' from 'PIL.ImageQt' (C:\Users\fabrice_senger\miniconda3\envs\SUPPORT\lib\site-packages\PIL\ImageQt.py)

**Comment by SteveJayH** [comment]
Hi, thank you for your attention to our SUPPORT.

It seems like there may be some errors related to Qt, mainly from the version issues.

I recall encountering a similar error in the past, which I resolved by reinstalling the packages with a different version.
However, I cannot recall the exact steps, so I'll make an effort to retrieve this information.

**In the meantime, actually the ImageQt module is not being used in the code, so Line 29 can be safely removed.
Please try removing it, and let us know if the problem goes well.**

Additionally, please note that the test_GUI is intended for a simple demonstration of our algorithm and may not be well-suited to your specific data. The best is to train the model based on your data. 

In any case, please check the test_GUI code if the error persists.
And for better results, we recommend training a model to your dataset.
If you encounter any difficulties in training, do not hesitate to reach out to us for assistance.

**Comment by fabricesenger** [comment]
Hi there and thank you for your quick reply.
I annotated line 29 and run the command again, new problem 👍 
(support) C:\Users\fabrice_senger\SUPPORT>python -m src.GUI.test_GUI
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by SteveJayH** [comment]
I'm not entirely certain about the nature of this error, but it appears that it might be related to crashes occurring across packages, based on my brief Google search.
As suggested in the hint, there is a straightforward method you can try. Add the following two lines at the beginning of the test_GUI code:

```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```

Please let me know if this resolves the issue!

**Comment by fabricesenger** [comment]
demo worked like a charm

**Comment by SteveJayH** [comment]
Glad to hear that!! 😄 

Please note that even though the output looks _**cool**_, using the pretrained model may result in inaccuracies that may not be visible in our eyes. (Since the pretrained model was trained with data different from yours.) For example, in functional imaging data, dF/F0 values could decrease in the denoised data with mismatched pretrained model)

Therefore, we recommend training the model specifically for your data **to achieve best performance**, especially if you try to adopt SUPPORT in your research!
Training is also very simple!
